version: "3.8"
services:
  todo-app:
    build: .
    container_name: todo-list-container
    ports:
      - "3000:3000"
    volumes:
      - ./src/dados.txt:/usr/src/app/src/dados.txt
    restart: always